import { Faculty } from "@/types/Faculty";

// Dummy data
const dummyFaculty: Faculty[] = [
    {
        id: 1,
        name: "Prof. Abhishek Srivastava",
        education: "PhD University of Alberta",
        designation: "Professor",
        specialization: " Service-Oriented Systems, Dynamic Systems, Geographically Distributed Development Environments, Agile Techniques, Software-as-a-Service",
        email: "asrivastava@iiti.ac.in",
        profileImagePath: "/facultypng/abhis.png",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://iiti.ac.in/people/~asrivastava/",
        contact: "+91-731-6603315",
    },
    {
        id: 2,
        name: "Prof. Aruna Tiwari",
        education: "PhD RGPV Bhopal",
        designation: "Professor",
        specialization: "Machine Learning, Soft-computing, Big Data, Data Mining, Deep Learning",
        email: "artiwari@iiti.ac.in",
        profileImagePath: "/facultypng/AT.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://iiti.ac.in/people/~artiwari/",
        contact: "+91-731-6603247",
    },
    {
        id: 3,
        name: "Prof. Anirban Sengupta",
        designation: "Professor",
        education: "PhD Ryerson University",
        specialization: " CAD-VLSI, EDA, High Level Synthesis, IP core Security, Hardware Trojan, Fault Security, Digital Watermark in digital chip, Optimization of Hardware Accelerators, Design Automation.",
        email: "anirban@iiti.ac.in",
        profileImagePath: "/facultypng/ProfAnirbanSengupta.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://www.anirban-sengupta.com/",
        contact: "+91-731-6603248",
    },
    {
        id: 4,
        name: "Prof. Surya Prakash",
        education: "PhD IIT Kanpur",
        designation: "Professor",
        specialization: "Biometrics, Machine Learning, Deep Learning",
        email: "surya@iiti.ac.in",
        profileImagePath: "/facultypng/surya.jpg",
        researchAreas: ["Cyber Security", "Networking", "Cryptography"],
        profileUrl: "https://people.iiti.ac.in/~surya/",
        contact: "+91-731-6603242",
    },
    {
        id: 5,
        name: "Prof. Somnath Dey",
        designation: "Professor",
        education: "PhD IIT Kharagpur",
        specialization: " Human Computer Interaction, Image Processing, Computer Graphics, Biometric Security.",
        email: "somnathd@iiti.ac.in",
        profileImagePath: "/facultypng/sd.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://somnathd.wixsite.com/somnath",
        contact: "+91-731-6603248",
    },
    {
        id: 6,
        name: "Prof. Kapil Ahuja",
        designation: "Professor",
        education: "PhD Virginia Tech",
        specialization: "Artificial Intelligence, Machine Learning, Soft Computing, Numerical Methods, Game Theory, and Optimization.",
        email: " kahuja@iiti.ac.in",
        profileImagePath: "/facultypng/kapil.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://kahuja.profiles.iiti.ac.in/",
        contact: "+91-731-6603226",
    },
    {
        id: 7,
        name: "Prof. Gourinath Banda",
        designation: "Professor",
        education: "PhD Roskilde University",
        specialization: "Embedded Systems (Cyber-physical systems, Internet-of-Things, Wireless Sensor Networks, etc.) and their Formal Verification (Model Checking, Abstract Interpretation, Program Transformation and Generation, Program Analysis),Semantics-based Emulation of Languages and Systems, Autonomous vehicles.",
        email: "gourinath@iiti.ac.in",
        profileImagePath: "/facultypng/gourinath.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://people.iiti.ac.in/~gourinath/",
        contact: "+91-731-6603245",
    },
    {
        id: 8,
        name: "Prof. Neminath Hubballi",
        designation: "Professor",
        education: "PhD IIT Guwahati",
        specialization: "Computer Networks, Network Security, System Security, Fault Detection in Networks",
        email: "neminath@iiti.ac.in",
        profileImagePath: "/facultypng/neminath.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://neminath.profiles.iiti.ac.in/",
        contact: "+91-731-6603246",
    },
    {
        id: 9,
        name: "Dr. Bodhisatwa Mazumdar ",
        designation: "Associate Professor",
        education: "PhD IIT Kharagpur",
        specialization: "Hardware Security, Side-channel Analysis, Cryptography, Digital VLSI Design.",
        email: "bodhisatwa@iiti.ac.in",
        profileImagePath: "/facultypng/bodhi_pic.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://people.iiti.ac.in/~bodhisatwa/",
        contact: "+91-731-6603249",
    },
    {
        id: 10,
        name: "Dr. Puneet Gupta",
        education: "PhD IIT Kanpur",
        designation: "Associate Professor",
        specialization: "Software Engineering, Agile Methodology",
        email: "puneet@iiti.ac.in",
        profileImagePath: "/facultypng/puneet_img.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://people.iiti.ac.in/~puneet/",
        contact: "+91-731-6603291",
    },
    {
        id: 11,
        name: "Dr. Nagendra Kumar",
        designation: "Assistant Professor",
        education: "PhD IIT Hyderabad",
        specialization: "Natural Language Processing, Social Network Analysis, Deep Learning, Data Mining.",
        email: "nagendra@iiti.ac.in",
        profileImagePath: "/facultypng/nagendra_photo.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://sites.google.com/view/nagendrak/",
        contact: "+91-731-6603225",
    },
    {
        id: 12,
        name: "Dr. Ranveer Singh",
        education: "PhD IIT Jodhpur",
        designation: "Associate Professor",
        specialization: "Algorithmic Graph Theory, Computational Complexity...",
        email: "ranveer@iiti.ac.in",
        profileImagePath: "/facultypng/Ranveer_Singh.jpg",
        researchAreas: ["AI", "Deep Learning", "Computer Vision"],
        profileUrl: "https://ranveeriit.github.io/",
        contact: "+91-731-6603224",
    },
    {
        id: 13,
        name: "Dr. Chandresh Kumar Maurya",
        designation: "Associate Professor",
        education: "PhD IIT Hyderabad",
        specialization: "Natural Language Processing, Social Network Analysis, Deep Learning, Data Mining.",
        email: "chandresh@iiti.ac.in",
        profileImagePath: "/facultypng/ckm.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://chandreshiit.github.io/ai-lab/",
        contact: "+91-731-6603225",
    },
    {
        id: 14,
        name: "Dr. Ayan Mondal",
        education: "PhD IIT Kharagpur",
        designation: "Assistant Professor",
        specialization: "Internet of Things (IoT) Networks, Softwarized Networks...",
        email: "ayanm@iiti.ac.in",
        profileImagePath: "/facultypng/ayan_2025.JPG",
        researchAreas: ["DBMS", "Cloud", "Distributed Systems"],
        profileUrl: "https://people.iiti.ac.in/~ayanm/",
        contact: "+91-731-6603426",

    },
    {
        id: 15,
        name: "Dr. Aniruddha Singh Kushwaha",
        designation: "Assistant Professor",
        education: "PhD IIT Bombay",
        specialization: "Software Defined Networking, Network Programmability, Datacenter networks.",
        email: "aniruddha@iiti.ac.in",
        profileImagePath: "/facultypng/Aniruddha.JPG",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://people.iiti.ac.in/~aniruddha/",
        contact: "+91-731-6603453 ",
    },
    {
        id: 16,
        name: "Dr. Sidharth Sharma (on lien)",
        designation: "Assistant Professor",
        education: "PhD IIT Bombay",
        specialization: "Network Softwarization and Management, Performance Modeling, Machine Learning for Networks, Network Algorithms.",
        email: "sidharth@iiti.ac.in",
        profileImagePath: "/facultypng/Sidharth.jpeg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://people.iiti.ac.in/~sidharth/",
        contact: " +91-731-6603442 ",
    },

    {
        id: 17,
        name: "Dr. Soumi Chattopadhyay",
        designation: "Assistant Professor",
        education: "PhD ISI Kolkata",
        specialization: "Services Computing, Artificial Intelligence, Machine Learning, Logic and Automated Reasoning.",
        email: "soumi@iiti.ac.in",
        profileImagePath: "/facultypng/Soumi.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://sites.google.com/site/soumi61/home",
        contact: " +91-731-6605579 ",
    },

    {
        id: 18,
        name: "Dr. Subhra Mazumdar",
        designation: "Assistant Professor",
        education: "PhD ISI Kolkata",
        specialization: "Applied Cryptography, Blockchain & Cryptocurrencies, Combinatorial Optimization.",
        email: "subhra.mazumdar@iiti.ac.in",
        profileImagePath: "/facultypng/subhra.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://sites.google.com/site/subhramazumdar1993/home",
        contact: " +91-731-6605579 ",
    },
    {
        id: 19,
        name: "Dr. Sasank Mouli",
        designation: "Assistant Professor",
        education: "PhD University of California San Diego",
        specialization: "Theoretical Computer Science, Proof complexity, Algebraic proof systems, Computational Complexity.",
        email: "sasankm@iiti.ac.in",
        profileImagePath: "/facultypng/Sasank.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://sasanks-webpage.webflow.io/",
        contact: " +91-91-731-6603305 ",
    },

    {
        id: 20,
        name: "Dr. Lawqueen Kanesh",
        designation: "Assistant Professor",
        education: "PhD Institute of Mathematical Sciences",
        specialization: "Parameterized/Approximation/Exact Algorithms, Graph Theory and Algorithms, Kernelization.",
        email: "lawqueen@iiti.ac.in",
        profileImagePath: "/facultypng/lawqueen.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://sites.google.com/view/lawqueenkanesh/home",
        contact: " +91-731-6603442",
    },
    {
        id: 21,
        name: "Dr. Debasish Pattanayak",
        designation: "Assistant Professor",
        education: "PhD IIT Guwahati",
        specialization: "Distributed Algorithms, Fault-tolerance, Swarm Robots, Randomized Algorithms, Graph Algorithms.",
        email: "debasish@iiti.ac.in",
        profileImagePath: "/facultypng/Debasish.jpg",
        researchAreas: ["Software Architecture", "Agile", "Testing"],
        profileUrl: "https://people.iiti.ac.in/~sidharth/",
        contact: " +91- ",
    },

];

// ... बाकी कोड वैसा ही रहेगा ...
export async function getFacultyMembers(): Promise<Faculty[]> {
    await new Promise((resolve) => setTimeout(resolve, 100));
    return dummyFaculty;
}