// lib/phdStudentData.ts

// 1. PhdStudent 'Type' को अपडेट करें
export interface PhdStudent {
    id: number;
    name: string;
    supervisor: string;
    category: string;       // 👈 यह जोड़ें
    rollNo: string;         // 👈 यह जोड़ें
    researchArea: string;
    email: string;
    profileImagePath: string;
}


const dummyPhdStudents: PhdStudent[] = [
    {
        id: 1,
        name: "Shaurya Sood",
        supervisor: "Prof. Neminath Hubballi",
        category: "DF",
        rollNo: "phd1801201007",
        researchArea: "Network Security",
        email: "phd1801201007@iiti.ac.in", // 👈 असली ईमेल डाला
        profileImagePath: "/phdpng/phd(40).jpg",
    },
    {
        id: 2,
        name: "Aparna Santra Biswas",
        supervisor: "Prof. Somnath Dey",
        category: "Full-Time",
        rollNo: "phd1901201008",
        researchArea: ": Biometrics Security",
        email: "phd1901201008@iiti.ac.in",
        profileImagePath: "/phdpng/phd2001201001_ap.jpg",
    },
    {
        id: 3,
        name: "Nayancy Gupta",
        supervisor: "Prof. Somnath Dey",
        category: "Full-Time",
        rollNo: "phd1901201008",
        researchArea: ": Biometrics Security",
        email: "phd1901201008@iiti.ac.in",
        profileImagePath: "/phdpng/2001201003.jpg",
    },
    {
        id: 4,
        name: "Pankaj Chaudhary",
        supervisor: "Prof. Gourinath Banda",
        category: "Full-Time",
        rollNo: "phd1901201008",
        researchArea: ": Biometrics Security",
        email: "phd1901201008@iiti.ac.in",
        profileImagePath: "/phdpng/2001201004_PANKAJCHAUDHARY.jpg",
    },
    {
        id: 5,
        name: "Saurabh Saini",
        supervisor: "Prof. Kapil Ahuja",
        category: "FA",
        rollNo: "phd2101101005",
        researchArea: ": Machine Learning / Explainable AI / Deep Learning",
        email: "phd2101101005@iiti.ac.in",
        profileImagePath: "/phdpng/phd2101101005_SaurabhSaini.jpg",
    },
    {
        id: 6,
        name: "Sneha Shukla",
        supervisor: "Dr. Puneet Gupta",
        category: "TA",
        rollNo: "phd2101101006",
        researchArea: ": Application of Deep Learning in Healthcare systems",
        email: "phd2101101006@iiti.ac.in",
        profileImagePath: "/phdpng/2101101006_SNEHA SHUKLA.jpg",
    },
    {
        id: 7,
        name: "Anup Kumar Gupta",
        supervisor: "Dr. Puneet Gupta",
        category: "FA-PMRF",
        rollNo: "msrphd2105101002",
        researchArea: ": Adversarial attacks and defences",
        email: "msrphd2105101002@iiti.ac.in",
        profileImagePath: "/phdpng/msrphd2105101002_Anup Kumar Gupta.jpg",
    },
    {
        id: 8,
        name: "Lalita Agrawal",
        supervisor: "Dr. Ayan Mondal",
        category: "TA",
        rollNo: "phd2101201003",
        researchArea: ": IoE enabled SDN and Edge Computing",
        email: "phd2101201003@iiti.ac.in",
        profileImagePath: "/phdpng/2101201003_LALITA AGRAWAL.jpg",
    },
    {
        id: 9,
        name: "Lipika Dewangan",
        supervisor: "Dr. Chandresh Kumar Maurya",
        category: "CT",
        rollNo: "phd2101201004",
        researchArea: ": Natural Language Processing,Machine Learning,Deep Learning,Social Network Analysis",
        email: "phd2101201004@iiti.ac.in",
        profileImagePath: "/phdpng/2101201004_ LIPIKA DEWANGAN.jpg",
    },
    {
        id: 10,
        name: "Mohammad Zia Ur Rehman",
        supervisor: "Dr. Nagendra Kumar",
        category: "FA",
        rollNo: "phd2101201005",
        researchArea: ": Natural Language Processing, Social Network Analysis, Deep Learning",
        email: "phd2101201005@iiti.ac.in",
        profileImagePath: "/phdpng/2101201005_MOHAMMAD ZIA UR REHMAN.jpg",
    },
    {
        id: 11,
        name: "Prasad Pradeeprao Kanhegaonkar",
        supervisor: "Prof. Surya Prakash",
        category: "QIP",
        rollNo: "phd2101201007",
        researchArea: ": Medical Image Analysis, Deep Learning",
        email: "phd2101201007@iiti.ac.in",
        profileImagePath: "/phdpng/2101201007_Prasad Pradeeprao Kanhegaonkar.jpg",
    },
    {
        id: 12,
        name: "Priyanka Upadhyay",
        supervisor: "Dr. Puneet Gupta",
        category: "SW",
        rollNo: "phd2101201008",
        researchArea: ": Machine Learning",
        email: "phd2101201008@iiti.ac.in",
        profileImagePath: "/phdpng/2101201008_PRIYANKA UPADHYAY.jpg",
    },
    {
        id: 13,
        name: "Kamanksha Prasad Dubey",
        supervisor: "Dr. Chandresh Kumar Maurya",
        category: "TA",
        rollNo: "phd2201101001",
        researchArea: ": Deep Learning, Natural Language Processing",
        email: "phd2201101001@iiti.ac.in",
        profileImagePath: "/phdpng/2201101001_KAMANKSHA PRASAD DUBEY.jpg",
    },
    {
        id: 14,
        name: "Abhishek Tripathi",
        supervisor: "Prof. Aruna Tiwari",
        category: "TA",
        rollNo: "phd2201101002",
        researchArea: ": Machine Learning",
        email: "phd2201101002@iiti.ac.in",
        profileImagePath: "/phdpng/2201101002_ABHISHEK TRIPATHI.jpg",
    },
    {
        id: 15,
        name: "Pragya Shrivastava",
        supervisor: "Prof. Neminath Hubballi",
        category: "FA",
        rollNo: "phd2201101003",
        researchArea: ": Smart -Grid Networks",
        email: "phd2201101003@iiti.ac.in",
        profileImagePath: "/phdpng/2201101003_PRAGYA SHRIVASTAVA.jpg",
    },
    {
        id: 16,
        name: "Mayank Ramnani",
        supervisor: "Dr. Sidharth Sharma",
        category: "TA",
        rollNo: "phd2201101004",
        researchArea: ": ",
        email: "phd2201101004@iiti.ac.in",
        profileImagePath: "/phdpng/2201101004_MAYANK RAMNANI.jpg",
    },
    {
        id: 17,
        name: "Priyanka Choudhary",
        supervisor: "Prof. Somnath Dey",
        category: "FA-UGC",
        rollNo: "phd2201101006",
        researchArea: ":Computer Vision and Machine Learning Applications",
        email: "phd2201101006@iiti.ac.in",
        profileImagePath: "/phdpng/2201101006_PRIYANKA CHOUDHARY.jpg",
    },
    {
        id: 18,
        name: "Lt Col Anshuman Agrahri",
        supervisor: "Dr. Chandresh Kumar Maurya",
        category: "DF",
        rollNo: "phd2201101008",
        researchArea: ":Machine Learning/ Artificial Intelligence",
        email: "phd2201101008@iiti.ac.in",
        profileImagePath: "/phdpng/2201101008_LT COL ANSHUMAN AGRAHRI.jpg",
    },
    {
        id: 19,
        name: "Aditya Dixit",
        supervisor: "Dr. Puneet Gupta",
        category: "FA-Project",
        rollNo: "phd2201101009",
        researchArea: ":Spatio-Spectral Deconvolution of Hyperspectral Images",
        email: "phd2201101009@iiti.ac.in",
        profileImagePath: "/phdpng/2201101009_ADITYA DIXIT.jpg",
    },
    {
        id: 20,
        name: "Yogendra Singh",
        supervisor: "Prof. Neminath Hubballi",
        category: "IS",
        rollNo: "phd2201101010",
        researchArea: ": ",
        email: "phd2201101010@iiti.ac.in",
        profileImagePath: "/phdpng/2201101010_YOGENDRA SINGH.jpg",
    },
    {
        id: 21,
        name: "Ankit Malviya",
        supervisor: "Dr. Chandresh Kumar Maurya",
        category: "SW",
        rollNo: "phd2201101011",
        researchArea: ": Multi Model Algorithm in NLP and Computer Vision for Speech and Text analysis",
        email: "phd2201101011@iiti.ac.in",
        profileImagePath: "/phdpng/2201101011_Ankit Malviya.jpg",
    },
    {
        id: 22,
        name: "Sharmila S P",
        supervisor: "Prof. Aruna Tiwari",
        category: "QIP",
        rollNo: "phd2201101012",
        researchArea: ": Cyber Security",
        email: "phd2201101012@iiti.ac.in",
        profileImagePath: "/phdpng/2201101012_Sharmila S P.jpg",
    },
    {
        id: 23,
        name: "Shekhar Tyagi",
        supervisor: "Prof. Abhishek Srivastava",
        category: "QIP",
        rollNo: "phd2201101013",
        researchArea: ": Wireless Sensor Networks ,Machine Learning , Algorithmic Optimizations",
        email: "phd2201101013@iiti.ac.in",
        profileImagePath: "/phdpng/2201101013_Shekhar Tyagi.jpg",
    },
    {
        id: 24,
        name: "Trishna Saikia",
        supervisor: "Dr. Puneet Gupta",
        category: "FA-PMRF",
        rollNo: "phd2201101014",
        researchArea: ": application of remote photoplethysmography in healthcare",
        email: "phd2201101014@iiti.ac.in",
        profileImagePath: "/phdpng/2201101014_Trishna Saikia.jpg",
    },
    {
        id: 25,
        name: "Kunvar Kanhaiya",
        supervisor: "Dr. Aniruddha Singh Kushwaha",
        category: "TA",
        rollNo: "phd2201101015",
        researchArea: ": Software Defined Networking",
        email: "phd2201101015@iiti.ac.in",
        profileImagePath: "/phdpng/2201101015_Kunvar Kanhaiya.jpg",
    },
    {
        id: 26,
        name: "Chandravardhan Singh Raghaw",
        supervisor: "Dr. Nagendra Kumar",
        category: "TA",
        rollNo: "phd2201101016",
        researchArea: ": Machine Learning, Deep Learning, Natural Language Processing",
        email: "phd2201101016@iiti.ac.in",
        profileImagePath: "/phdpng/2201101016_Chandravardhan Singh Raghaw.jpg",
    },
    {
        id: 27,
        name: "Doli Uppal",
        supervisor: "Prof. Surya Prakash",
        category: "TA",
        rollNo: "phd2201201001",
        researchArea: ": Medical Image Analysis, Deep Learning",
        email: "phd2201201001@iiti.ac.in",
        profileImagePath: "/phdpng/dolli.jpg",
    },
    {
        id: 28,
        name: "Nivedita Sethiya",
        supervisor: "Dr. Chandresh Kumar Maurya",
        category: "FA",
        rollNo: "phd2201201003",
        researchArea: ": Speech Processing, Natural Language Processing, Deep Learning and Indic Languages",
        email: "phd2201201003@iiti.ac.in",
        profileImagePath: "/phdpng/nivedita.jpg",
    },
    {
        id: 29,
        name: "Shahid Shafi Dar",
        supervisor: "Dr. Nagendra Kumar",
        category: "TA",
        rollNo: "phd2201201004",
        researchArea: ": SNatural Language Processing, Deep Learning and Social Network Analysis",
        email: "phd2201201004@iiti.ac.in",
        profileImagePath: "/phdpng/Shahid.jpg",
    },
    {
        id: 30,
        name: "Sujata Gudge",
        supervisor: "Prof. Aruna Tiwari",
        category: "FA",
        rollNo: "phd2201201005",
        researchArea: ": Artificial Intelligence",
        email: "phd2201201005@iiti.ac.in",
        profileImagePath: "/phdpng/sujata.jpg",
    },
    {
        id: 31,
        name: "Veerendra Kumar Datta",
        supervisor: "Dr. Ayan Mondal",
        category: "DF",
        rollNo: "phd2201201006",
        researchArea: ": Software-Defined Networking (SDN)",
        email: "phd2201201006@iiti.ac.in",
        profileImagePath: "/phdpng/vkdatta.jpg",
    },
    {
        id: 32,
        name: "Pralhad Magadum",
        supervisor: "Dr. Aniruddha Singh Kushwaha",
        category: "FA-MaiTY",
        rollNo: "phd2201201007",
        researchArea: ": Computer Networks",
        email: "phd2201201007@iiti.ac.in",
        profileImagePath: "/phdpng/pralhad.jpg",
    },
    // The four records you wanted to insert in IDs 33-36:
    {
        id: 33,
        name: "Suraj Kumar",
        supervisor: "Dr. Soumi Chattopadhyay",
        category: "TA",
        rollNo: "phd2301101002",
        researchArea: ": Service Recommendation, Machine Learning, Graph Representation Learning",
        email: "phd2301101002@iiti.ac.in",
        profileImagePath: "/phdpng/Suraj Kumar.jpg",
    },
    {
        id: 34,
        name: "Mrunal Kewalram Shende",
        supervisor: "Dr. Bodhisatwa Mazumdar",
        category: "TA",
        rollNo: "phd2301101003",
        researchArea: ": Emerging Logic Synthesis Techniques and Associated Security Implications.",
        email: "phd2301101003@iiti.ac.in",
        profileImagePath: "/phdpng/Mrunal Kewalram Shende.jpg",
    },
    {
        id: 35,
        name: "Virendra Singh",
        supervisor: "Dr. Ranveer Singh",
        category: "TA",
        rollNo: "phd2301101004",
        researchArea: ": Algorithms",
        email: "phd2301101004@iiti.ac.in",
        profileImagePath: "/phdpng/Virendra Singh.jpg",
    },
    {
        id: 36,
        name: "Rinku Kumar",
        supervisor: "Dr. Bodhisatwa Mazumdar",
        category: "TA",
        rollNo: "phd2301101005",
        researchArea: ": Temporal Graphs, Parameterized Complexity",
        email: "phd2301101005@iiti.ac.in",
        profileImagePath: "/phdpng/Rinku Kumar.jpg",
    },
    // Original records from ID 33 onwards are now re-indexed starting from 37:
    {
        id: 37,
        name: "Aravind Ramagiri",
        supervisor: "Dr. Puneet Gupta",
        category: "TA",
        rollNo: "phd2301101006",
        researchArea: ": Deep Learning",
        email: "phd2301101006@iiti.ac.in",
        profileImagePath: "/phdpng/Aravind Ramagiri.jpg",
    },
    {
        id: 38,
        name: "Pappoppula Muni Kumar",
        supervisor: "Prof. Surya Prakash",
        category: "SW",
        rollNo: "phd2301101007",
        researchArea: ": ",
        email: "phd2301101007@iiti.ac.in",
        profileImagePath: "/phdpng/Pappoppula Muni Kumar.jpg",
    },
    {
        id: 39,
        name: "Mayank Gautam",
        supervisor: "Prof. Neminath Hubballi",
        category: "DF",
        rollNo: "phd2301101008",
        researchArea: ": ",
        email: "phd2301101008@iiti.ac.in",
        profileImagePath: "/phdpng/Mayank Gautam.jpg",
    },
    {
        id: 40,
        name: "Kuldeep Pathak",
        supervisor: "Prof. Kapil Ahuja",
        category: "TA",
        rollNo: "phd2301101009",
        researchArea: ": Machine Learning",
        email: "phd2301101009@iiti.ac.in",
        profileImagePath: "/phdpng/Kuldeep Pathak.jpg",
    },
    {
        id: 41,
        name: "Prashant Digambar Pathak",
        supervisor: "Prof. Surya Prakash",
        category: "QIP",
        rollNo: "phd2301101010",
        researchArea: ": Deep Learning based Biometrics for cattle identification",
        email: "phd2301101010@iiti.ac.in",
        profileImagePath: "/phdpng/Kuldeep Pathak.jpg",
    },
    {
        id: 42,
        name: "Haresh Kumar Jadhav",
        supervisor: "Dr. Ranveer Singh",
        category: "TA",
        rollNo: "phd2301106001",
        researchArea: ": ",
        email: "phd2301106001@iiti.ac.in",
        profileImagePath: "/phdpng/2301106001_Haresh.jpg",
    },
    {
        id: 43,
        name: "Rajesh Kumar",
        supervisor: "Dr. Puneet Gupta",
        category: "FA",
        rollNo: "phd2301201002",
        researchArea: ": ",
        email: "phd2301201002@iiti.ac.in",
        profileImagePath: "/phdpng/rajesh.jpg",
    },
    {
        id: 44,
        name: "Shalini Dangi",
        supervisor: "Dr. Nagendra Kumar",
        category: "FA",
        rollNo: "phd2301201003",
        researchArea: ": Machine Learning, Deep Learning, Computer Vision",
        email: "phd2301201003@iiti.ac.in",
        profileImagePath: "/phdpng/shalini.jpg",
    },
    {
        id: 45,
        name: "Shilpy Kaur",
        supervisor: "Prof. Aruna Tiwari",
        category: "FA",
        rollNo: "phd2301201004",
        researchArea: ": Artificial Intelligence",
        email: "phd2301201004@iiti.ac.in",
        profileImagePath: "/phdpng/shilpy.jpg",
    },
    {
        id: 46,
        name: "Arvind Kumar",
        supervisor: "Dr. Soumi Chattopadhyay",
        category: "TA",
        rollNo: "phd2401101001",
        researchArea: ": Machine learning with multi - task learning recommendations system",
        email: "phd2401101001@iiti.ac.in",
        profileImagePath: "/phdpng/2401101001_ARVIND KUMAR.jpg",
    },
    {
        id: 47,
        name: "Bibhas Kumar Rana",
        supervisor: "Prof. Gourinath Banda",
        category: "DF",
        rollNo: "phd2401101002",
        researchArea: ": IoT and cyber security",
        email: "phd2401101002@iiti.ac.in",
        profileImagePath: "/phdpng/2401101002_BIBHAS KUMAR RANA.jpg",
    },
    {
        id: 48,
        name: "Kailash Kumar",
        supervisor: "Dr. Puneet Gupta",
        category: "DF",
        rollNo: "phd2401101003",
        researchArea: ": ",
        email: "phd2401101003@iiti.ac.in",
        profileImagePath: "/phdpng/2401101003_KAILASH KUMAR.jpg",
    },
    {
        id: 49,
        name: "Nabendu Bhui",
        supervisor: "Prof. Anirban Sengupta",
        category: "TA",
        rollNo: "phd2401101004",
        researchArea: ": Hardware Security",
        email: "phd2401101004@iiti.ac.in",
        profileImagePath: "/phdpng/2401101004_NABENDU BHUI.jpg",
    },
    {
        id: 50,
        name: "Rituraj Patel",
        supervisor: "Dr. Anirudha Singh Kushwaha",
        category: "TA",
        rollNo: "phd2401101006",
        researchArea: ": ",
        email: "phd2401101006@iiti.ac.in",
        profileImagePath: "/phdpng/2401101006_RITURAJ PATEL.jpg",
    },
    {
        id: 51,
        name: "Sangita Kumari",
        supervisor: "Prof. Surya Prakash",
        category: "DF",
        rollNo: "phd2401101007",
        researchArea: ": ",
        email: "phd2401101007@iiti.ac.in",
        profileImagePath: "/phdpng/2401101007_SANGITA KUMARI.jpg",
    },
    {
        id: 52,
        name: "Soumya Pandey",
        supervisor: "Dr. Soumi Chattopadhyay",
        category: "TA",
        rollNo: "phd2401101008",
        researchArea: ": ",
        email: "phd2401101008@iiti.ac.in",
        profileImagePath: "/phdpng/2401101008_SOUMYA PANDEY.jpg",
    },
    {
        id: 53,
        name: "Sudhanshu Trivedi",
        supervisor: "Prof. Abhishek Srivastava",
        category: "TA",
        rollNo: "phd2401101009",
        researchArea: ": Artificial Intelligence in Health",
        email: "phd2401101009@iiti.ac.in",
        profileImagePath: "/phdpng/2401101009_SUDHANSHU TRIVEDI.jpg",
    },
    {
        id: 54,
        name: "Sumit Shevtekar",
        supervisor: "Dr. Chandresh Kumar Maurya",
        category: "QIP",
        rollNo: "phd2401101010",
        researchArea: ": AI,ML,DL,Two Wheeler Safety",
        email: "phd2401101010@iiti.ac.in",
        profileImagePath: "/phdpng/2401101010_SUMIT SHEVTEKAR.jpg",
    },
    {
        id: 55,
        name: "Bhavesh Agrwal",
        supervisor: "Dr. Nagendra Kumar",
        category: "TA",
        rollNo: "phd2401101011",
        researchArea: ": ",
        email: "phd2401101011@iiti.ac.in",
        profileImagePath: "/phdpng/2401101011_BHAVESH AGRAWAL.jpg",
    },
    {
        id: 56,
        name: "Aryan Alpesh Bhavsar",
        supervisor: "Dr. Ayan Mondal",
        category: "FA",
        rollNo: "phd2401201001",
        researchArea: ": ",
        email: "phd2401201001@iiti.ac.in",
        profileImagePath: "/phdpng/2401201001_Aryan Alpesh Bhavsar.jpeg",
    },
    {
        id: 57,
        name: "Chinnala Abhilash",
        supervisor: "Dr. Subhra Mazumdar",
        category: "FA",
        rollNo: "phd2401201002",
        researchArea: ": Scalable solutions in blockchain",
        email: "phd2401201002@iiti.ac.in",
        profileImagePath: "/phdpng/2401201002_CHINNALA ABHILASH.jpg",
    },
    {
        id: 58,
        name: "Shivam Sharma",
        supervisor: "Dr. Bodhisatwa Mazumdar",
        category: "FA",
        rollNo: "phd2401201003",
        researchArea: ": Cryptography.",
        email: "phd2401201003@iiti.ac.in",
        profileImagePath: "/phdpng/2401201003_shivam.jpg",
    },
    {
        id: 59,
        name: "Abhimanyu Singh",
        supervisor: "Dr. Puneet Gupta",
        category: "DF",
        rollNo: "phd2401201004",
        researchArea: ": Cryptography.",
        email: "phd2401201004@iiti.ac.in",
        profileImagePath: "/phdpng/2401201004.jpg",
    },
    {
        id: 60,
        name: "Apurv Anand",
        supervisor: "Dr. Puneet Gupta",
        category: "TA",
        rollNo: "phd2401201005",
        researchArea: ": ",
        email: "phd2401201005@iiti.ac.in",
        profileImagePath: "/phdpng/2401201005.jpg",
    },
    {
        id: 61,
        name: "Nikita Tiwari",
        supervisor: "",
        category: "TA",
        rollNo: "phd2401201006",
        researchArea: ": ",
        email: "phd2401201006@iiti.ac.in",
        profileImagePath: "/phdpng/2401201006.jpg",
    },
    {
        id: 62,
        name: "Manoj Kumar",
        supervisor: "Prof. Gourinath Banda",
        category: "DF",
        rollNo: "phd2401201007",
        researchArea: ": ",
        email: "phd2401201007@iiti.ac.in",
        profileImagePath: "/phdpng/2401201007.jpeg",
    },
    {
        id: 63,
        name: "Priyanshu Kumar Pant",
        supervisor: "Dr. Ranveer Singha",
        category: "FA",
        rollNo: "phd2401201008",
        researchArea: ": ",
        email: "phd2401201008@iiti.ac.in",
        profileImagePath: "/phdpng/2401201008.jpg",
    },
    {
        id: 64,
        name: "Vishal Chourasia",
        supervisor: "Prof. Anirban Sengupta",
        category: "FA",
        rollNo: "phd2401201010",
        researchArea: ": ",
        email: "phd2401201010@iiti.ac.in",
        profileImagePath: "/phdpng/2401201010.jpg",
    },
    {
        id: 65,
        name: "Anamika Mangore",
        supervisor: "Dr. Ayan Mondal",
        category: "TA",
        rollNo: "phd2501101001",
        researchArea: ": ",
        email: "phd2501101001@iiti.ac.in",
        profileImagePath: "/phdpng/2501101001.jpeg",
    },
    {
        id: 66,
        name: "Anurag Soni",
        supervisor: "Dr. Lawqueen Kanesh",
        category: "TA",
        rollNo: "phd2501101002",
        researchArea: ": ",
        email: "phd2501101002@iiti.ac.in",
        profileImagePath: "/phdpng/2501101002.jpg",
    },
    {
        id: 67,
        name: "Gaurav Tiwari",
        supervisor: "Prof. Aruna Tiwari",
        category: "TA",
        rollNo: "phd2501101006",
        researchArea: ": ",
        email: "phd2501101006@iiti.ac.in",
        profileImagePath: "/phdpng/2501101006.jpg",
    },
    {
        id: 68,
        name: "Sorbajit Goswami",
        supervisor: "Dr. Subhra Mazumdar",
        category: "TA",
        rollNo: "phd2501101007",
        researchArea: ": ",
        email: "phd2501101007@iiti.ac.in",
        profileImagePath: "/phdpng/2501101007.jpg",
    },
    {
        id: 69,
        name: "Veerendra Shrivastava",
        supervisor: "Prof. Aruna Tiwari",
        category: "FAP",
        rollNo: "phd2501101008",
        researchArea: ": ",
        email: "phd2501101008@iiti.ac.in",
        profileImagePath: "/phdpng/2501101008.jpg",
    },
    {
        id: 70,
        name: "Yashpal",
        supervisor: "Dr. Lawqueen Kanesh",
        category: "TA",
        rollNo: "phd2501101009",
        researchArea: ": ",
        email: "phd2501101009@iiti.ac.in",
        profileImagePath: "/phdpng/2501101009.jpg",
    },
    {
        id: 71,
        name: "Avinash Bharti",
        supervisor: "Prof. Aruna Tiwari",
        category: "TA",
        rollNo: "phd2501101010",
        researchArea: ": ",
        email: "phd2501101010@iiti.ac.in",
        profileImagePath: "/phdpng/2501101010.jpeg",
    },
    {
        id: 72,
        name: "Khushi Koshta",
        supervisor: "Dr. Soumi Chattopadhyay",
        category: "TA",
        rollNo: "phd2501101012",
        researchArea: ": India AI",
        email: "phd2501101012@iiti.ac.in",
        profileImagePath: "/phdpng/2501101012.jpg",
    },
    {
        id: 73,
        name: "Vipendra Singh",
        supervisor: "Dr. Puneet Gupta",
        category: "TA",
        rollNo: "mscphd2303141018",
        researchArea: ": ",
        email: "mscphd2303141018@iiti.ac.in",
        profileImagePath: "/phdpng/2303141018.jpg",
    },
    {
        id: 74,
        name: "Sourabh Singh",
        supervisor: "Dr. Aniruddha Singh Kushwaha",
        category: "TA",
        rollNo: "msrphd2304101012",
        researchArea: ": ",
        email: "msrphd2304101012@iiti.ac.in",
        profileImagePath: "/phdpng/Sourabh Singh.jpg",
    },
]


;

// 3. फ़ंक्शन (getPhdStudents) वैसा ही रहेगा
export async function getPhdStudents(): Promise<PhdStudent[]> {
    await new Promise((resolve) => setTimeout(resolve, 100));
    return dummyPhdStudents;
}